Add article cell phone ruined generation
Perspicere/perspicere.github.io pull request #4
Opened 2018-05-30 14:36 UTC by jsonchi

https://www.douban.com/note/669686393/
新一篇已提交 @guoliu

2018-05-30 17:40 UTC, guoliu requested changes

2018-05-30 17:40 UTC, guoliu commented on articles/cell-phone-ruined-generation/article.md
> +editor: '刘果、角角'
这里是否可以把顿号换成英文逗号？之后用程序读取英文标点的支持会好一点。

2018-05-31 08:01 UTC, jsonchi commented on articles/cell-phone-ruined-generation/article.md
> +editor: '刘果、角角'
当时也想过用逗号，但是不知道程序有这个逻辑。我再修改下

2018-05-31 19:43 UTC, guoliu approved these changes

2018-05-31 19:43 UTC, merged